services:
  web_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        REQUIREMENTS: requirements/production.txt
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      ENVIRONMENT: ${ENVIRONMENT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db_postgres
      command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db_production
    networks:
      - app-network

  db_production:
    image: postgres:17-alpine
    container_name: db_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ../allegro-clone-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://web_prod:8000
    depends_on:
      - web_prod

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web_prod

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3100:3000"
    depends_on:
      - web_prod

networks:
  app-network: